### ISSUE TITLE
Bugs in new releases after code refactoring

### ISSUE THREAD

**Issue by fabioamc** [GIBIS-UNIFESP/wiRedPanda#123]
- Bug in coping and pasting circuits. Some wires are duplicated in the source circuit and missing in the cloned one.
- right click shortcut is reactivated after morphing an element to another.
- interface is slower than before, having very long stalls
- after morphing Node into a Not, the Not is rotated to an undesired position.
- Shift+left click does not add/remove elements to/from the selection, but duplicates selected items. This behavior is expected only for Ctrl+left click command.
- Inputs and outputs connectors appear rotated.
- scrolling in dolphin window is not working properly.

**Comment by fabioamc** [comment]
Copy-paste fails when selecting an area with an element and its connections, without the elements it connects from/to.
E.g. In a new project, link a button to a LED. Then, select the button by selecting an area around it and copy-paste.
The selected area will include the connection (wire), but not the LED.
The correct behavior is to paste the elements with all selected connections with both ends in it, leaving the other connections out.

**Comment by darktorres** [comment]
Fixed the copy paste bug.
Reverted today a change in the GraphicsView viewport update mode. Should be back to pre-refactoring speed.
Also improved mouseMoveEvent speed.

**Comment by fabioamc** [comment]
beWavedDolphin crashes when setting length waveform to 2048 and selecting maximum zoom out. (Tested on Windows)

**Comment by darktorres** [comment]
I tried here and Dolphin crashes if asked to resize to a size of 10.000x10.000 or bigger. Can I change the blue and green lines so they are smaller?

**Comment by darktorres** [comment]
Sent some fixes. There is still a crash when morphing several elements all at once but I'm investigating here.

**Comment by darktorres** [comment]
Fixed the morph crash.

**Comment by fabioamc** [comment]
> I tried here and Dolphin crashes if asked to resize to a size of 10.000x10.000 or bigger. Can I change the blue and green lines so they are smaller?

Sure, if it fixes and is still visible, it is fine.

**Comment by darktorres** [comment]
@fabioamc 
> * [ ]  Morphing operation now only works on elements with the same number of ports. This is not the intended behavior. To replicate this bug, add two AND ports into the canvas, each of them with a different number of input ports, select them, and try to morph into another kind of port. The option to do that will not appear.

I looked here and the code that blocks this morphing operation was present before the refactoring. I can disable the code but just need to confirm first.

https://github.com/GIBIS-UNIFESP/wiRedPanda/blob/c414299f38389ca5a832bd6b740fa5168e4985d7/app/elementeditor.cpp#L332

**Comment by fabioamc** [comment]
> @fabioamc
> 
> > * [ ]   Morphing operation now only works on elements with the same number of ports. This is not the intended behavior. To replicate this bug, add two AND ports into the canvas, each of them with a different number of input ports, select them, and try to morph into another kind of port. The option to do that will not appear.
> 
> I looked here and the code that blocks this morphing operation was present before the refactoring. I can disable the code but just need to confirm first.
> 
> https://github.com/GIBIS-UNIFESP/wiRedPanda/blob/c414299f38389ca5a832bd6b740fa5168e4985d7/app/elementeditor.cpp#L332

I am not sure if that validation is important for CIs.
If not, then you may revert it.
