### ISSUE TITLE
Blue wire highlighting error, while selecting an element connected to a node.

### ISSUE THREAD

**Issue by fabioamc** [GIBIS-UNIFESP/wiRedPanda#148]
If you select an element (gate, input, output, memory) connected to a node, not only all wires connected to it are highlighted in blue, but also all other wires connected to the node.
This is not desirable, since you may select the node and the element to have the same behavior.
![panda_highlight_error](https://user-images.githubusercontent.com/12301501/236297903-bce46997-049b-4360-bb7e-57dac2994ca2.png)

**Comment by darktorres** [comment]
Fixed in 3026afd7a124cf1675c5e58b74d6b1c4634b4569
