### ISSUE TITLE
Crash when releasing a wire while holding control

### ISSUE THREAD

**Issue by rpeixe** [GIBIS-UNIFESP/wiRedPanda#159]
When holding a wire, either pressing or releasing the left mouse button while holding the Control key crashes the application.

Steps to reproduce:
-
- Create any input/output or gate
- Hold control
- Mouse over any port and hold left mouse button
- Drag the wire to an empty space
- Release the left mouse button
- Can also be done by clicking an port, then holding control and clicking an empty space 

Version: 4.1.11
OS: Windows 10 21H2

**Comment by darktorres** [comment]
Fixed in 4.1.12 4f019dfc2d0759986738174797a46fad97c73921
