### ISSUE TITLE
Nao estou conseguindo abrir o programa

### ISSUE THREAD

**Issue by ivandardi** [GIBIS-UNIFESP/wiRedPanda#21]
Mensagem de erro:

`./wpanda: error while loading shared libraries: libicui18n.so.52: cannot open shared object file: No such file or directory`

**Comment by lellisls** [comment]
Oi Ivan, poderia me passar qual sistema operacional e arquitetura está utilizando?
Se for um computador de algum lab. da Unifesp, vc pode me passar a sala?

**Comment by ivandardi** [comment]
Intel® Core™ i3-2350M CPU @ 2.30GHz × 4 
Ubuntu 15.10 64-bit

Eh o meu proprio laptop.

**Comment by lellisls** [comment]
Olá Ivan, desculpe a demora.
A sua versão do ubuntu estava a frente da que utilizamos para compilar o software e por isso houve certas incompatibilidades.
Demoramos bastante, mas creio que conseguimos resolver o problema!

Utilize os pacotes abaixo e me dá um feedback se funcionar, por favor.

Novo instalador: [WiredPanda_1_9_Ubuntu_Installer_x86_64.deb](https://github.com/GIBIS-UNIFESP/wiRedPanda/releases/download/v1.9-beta/WiredPanda_1_9_Ubuntu_Installer_x86_64.deb)

Versão portátil: [WiredPanda_1_9_Ubuntu_Portable_x86_64.tar.gz](https://github.com/GIBIS-UNIFESP/wiRedPanda/releases/download/v1.9-beta/WiredPanda_1_9_Ubuntu_Portable_x86_64.tar.gz)

Já adiantando, muito obrigado por relatar esse problema, foi de grande ajuda.

Att.
Lucas Lellis

**Comment by lellisls** [comment]
Obs. Os links dos pacotes podem ter sido alterados, então utilize o link abaixo:

[https://github.com/GIBIS-UNIFESP/wiRedPanda/releases/edit/v1.9-beta](https://github.com/GIBIS-UNIFESP/wiRedPanda/releases/edit/v1.9-beta)

**Comment by ivandardi** [comment]
O portable esta funcionando. O instalador nao ta, mas eu acho que e porque eu ainda tenho a versao antiga instalada. Valeu por consertar ai :)

**Comment by lellisls** [comment]
Tenta dar um `sudo dpkg --purge wpanda`
