### ISSUE TITLE
Simulação não propaga sinais inválidos

### ISSUE THREAD

**Issue by lellisls** [GIBIS-UNIFESP/wiRedPanda#22]
Este NOT deveria ter saída vermelha!
![screenshot-wired panda](https://cloud.githubusercontent.com/assets/7882921/14232624/86b575a0-f986-11e5-8fd6-bad0f943227c.png)

Ideia:
- Implementar algoritmo externo que identifica, desenha e lista todos os erros.

**Comment by fabioamc** [comment]
Lucas, acho que você tinha razão.
Isso não é um bug. Vamos deixar como está.
Se não, teremos problemas com elementos de memória.

Abraço 

Enviado do meu iPad

**Comment by lellisls** [comment]
Estou pensando se não teria como implementar uma função que percorre o
circuito ( busca em profundidade ) propagando os erros.


Em dom, 3 de abr de 2016 às 12:42, Fábio Augusto Menocci Cappabianco <
notifications@github.com> escreveu:

> Lucas, acho que você tinha razão.
> Isso não é um bug. Vamos deixar como está.
> Se não, teremos problemas com elementos de memória.
>
> Abraço
>
> Enviado do meu iPad
>
> > Em 3 de abr de 2016, às 10:28, Lucas Santana Lellis <
> notifications@github.com> escreveu:
> >
> > Este NOT deveria ter saída vermelha!
> >
> >
> > Ideia:
> >
> > Implementar algoritmo externo que identifica, desenha e lista todos os
> erros.
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GIBIS-UNIFESP/wiRedPanda/issues/22#issuecomment-205000077>
>
-- 
Lucas Lellis
