### ISSUE TITLE
Application startup fails on Artix Linux

### ISSUE THREAD

**Issue by AuroransSolis** [GIBIS-UNIFESP/wiRedPanda#26]
Just recently downloaded the wiRedPanda AppImage file off the website, did the ol' chmod u+x, and tried to run it. Instead of the program launching, however, I got this error:
```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted
```
I'm not sure what to do, since I have basically everything necessary and/or related to Qt installed that shows up with `pacman -Ss xcb`.

System info:
OS: Artix Linux x86_64
Kernel: 4.18.6-artix1-1-ARTIX

**Comment by darktorres** [comment]
Tested on a current image of Artix, seems to be working. Please reopen if still having issues.
